name: Fast
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  call_test_workflow:
    name: testing
    uses: ./.github/workflows/test.yml
  pull:
    needs: call_test_workflow
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/fastapi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/newsmakers-backend:latest
  deploy:
    needs: pull
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /app/newsmakers/
          docker compose down
          docker compose pull fastapi
          docker compose --env-file .env.upd up -d
